### ISSUE TITLE
Comment mess up the output

### ISSUE THREAD

**Issue by vors** [vors/jupyter-powershell#10]
Try create few cells with comments on top of them

![image](https://user-images.githubusercontent.com/816680/38958795-95a6e8ae-435e-11e8-88ee-f4a863d35e96.png)

**Comment by chlafreniere** [comment]
We've got some folks running into this issue. Would it be best to just not pass commented lines to powershell, or is there a sneaky PS workaround like the . { <code> } that we can leverage 😄?

**Comment by vors** [comment]
Is it still happening with the `. {}` hack?

**Comment by chlafreniere** [comment]
Spoke too soon. Looks like it's fixed now with the `. {}` hack

**Comment by vors** [comment]
sweet
