### ISSUE TITLE
publish release 0.1.0

### ISSUE THREAD

**Issue by vors** [vors/jupyter-powershell#18]
We need to publish release 0.1.0 but looks like pypl changed toolchain to some new tool https://twine.readthedocs.io/en/latest/ . If somebody want to figure out the publishing story for that packages, that would be awesome. I will help with providing access to the package.

**Comment by kevcunnane** [comment]
Looking at https://pypi.org/project/publish/, seems like you should just need github and PyPi credentials? Then set as:
```sh
export GITHUB_TOKEN=gh-token
export TWINE_USERNAME=pypi-user
export TWINE_PASSWORD=pypi-pass
```
and run publish? Happy to help (I work on Azure Data Studio team and want to use updated package), just let me and @chlafreniere what you might need help with and we can try to assist.

**Comment by vors** [comment]
@chlafreniere do you want to take over release publishing?
I can add you as maintainer to the package on pypi.

**Comment by chlafreniere** [comment]
Absolutely, more than happy to do it!

**Comment by vors** [comment]
Cool, just tell me the username on https://pypi.org/ and I will add you.

**Comment by chlafreniere** [comment]
chlafren. Thanks, @vors!

**Comment by vors** [comment]
done https://pypi.org/project/powershell_kernel/

**Comment by TRM13** [comment]
Thank you vors for getting the ball rolling and thanks to chlafreniere & kevcunnane for keeping it going. I submitted the request to Microsoft that they should formally do up a Powershell kernel for Jupyter as it is the best way to teach scripting and programming I've seen. Maybe Kev can prod them. 

Thanks again everyone.

**Comment by vors** [comment]
Looks like it's out. @chlafreniere can you, please, send a PR with publish instructions to the repo, so we don't forget how to do it?
