### ISSUE TITLE
No printing of intermediate results.

### ISSUE THREAD

**Issue by lerchdude** [vors/jupyter-powershell#37]
Something like:
```
Write-Output "Hello"
Start-Sleep -Seconds 2
```
Will wait for the sleep to complete before printing "Hello".

Using version 0.1.3 of the kernel in a notebook running in azuredatastudio-insiders 1.16.0-insider

**Comment by lerchdude** [comment]
@chlafreniere Let me know if I should file this to ADS instead.

**Comment by lerchdude** [comment]
@VasuBhog looks like you just fixed this!

**Comment by VasuBhog** [comment]
@lerchdude Yup! The PowerShell kernel will support interactive streaming output that will be announced in the October release of ADS next week! (should be able to use it now as well 👍 )

**Comment by lerchdude** [comment]
Okay cool can you link #39  to this issue and close it?
