### ISSUE TITLE
_

### ISSUE THREAD

**Issue by ghost** [vors/jupyter-powershell#4]
_

**Comment by vors** [comment]
Hi! I didn't try it on mac at all and it will probably be a non-trivial change, because of windows specific python apis used.
Take a look at another powershell jupyter kernel https://github.com/Jaykul/Jupyter-PowerShell it should support all platforms.

**Comment by vors** [comment]
@megamindbrian after hitting hard problems with  https://github.com/Jaykul/Jupyter-PowerShell I made this kernel mac compatible, so if you are still interested install the 0.0.5 version.

**Comment by ghost** [comment]
_
